[project]
name = "xeno-canto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aider-chat>=0.79.2",
    "awscli>=1.38.23",
    "boto3>=1.37.23",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
